[language-server.clangd]
command = "clangd"
args = [
  "--clang-tidy",
  "--fallback-style=WebKit",
  "--header-insertion=never"
]

[[language]]
name = "scheme"
language-servers = ["steel-language-server"]

[language-server.steel-language-server]
command = "steel-language-server"
args = []

# [[language]]
# name = "rust"

# [language.debugger]
# name = "lldb-dap"
# transport = "stdio"
# command = "lldb-dap"

# [[language.debugger.templates]]
# name = "binary"
# request = "launch"
# completion = [ { name = "binary", completion = "filename" } ]
# args = { program = "{0}", initCommands = [ "command script import ~/.config/lldb-dap/rustc_primer.py" ] }
